name: Build Image

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - asdf

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            image:
              - '${{ matrix.image }}.Dockerfile'
              - '${{ matrix.image }}/**'
      - run: >-
          docker build
          -t ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.run_number }}.${{ github.run_attempt }}
          -f ${{ matrix.image }}.Dockerfile
          .
        if: steps.filter.outputs.image == 'true'
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u $ --password-stdin ghcr.io
        name: Login to registry
        if: ${{ github.event_name == 'push' && steps.filter.outputs.image == 'true' }}
      - run: docker push ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.run_number }}.${{ github.run_attempt }}
        if: ${{ github.event_name == 'push' && steps.filter.outputs.image == 'true' }}
